[[USRPHardwareDriver]]
arch = "aarch64"
git-tree-sha1 = "ed16252dc4230985e94a6bd47f39c86ef29f51d3"
os = "macos"

    [[USRPHardwareDriver.download]]
    sha256 = "2aa7d5ef98db640ff8c7113c290ffee10d606f7337ecd5e2257b3d8a356b062d"
    url = "https://github.com/JuliaBinaryWrappers/USRPHardwareDriver_jll.jl/releases/download/USRPHardwareDriver-v4.1.0+0/USRPHardwareDriver.v4.1.0.aarch64-apple-darwin.tar.gz"
[[USRPHardwareDriver]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "57068b7bbb2264f6e4d37a5da723b46dbccad6dd"
libc = "glibc"
os = "linux"

    [[USRPHardwareDriver.download]]
    sha256 = "b7c7e3540ee0f196109b066ef075990d98ce2f613033bd104d9114bc7059d9d2"
    url = "https://github.com/JuliaBinaryWrappers/USRPHardwareDriver_jll.jl/releases/download/USRPHardwareDriver-v4.1.0+0/USRPHardwareDriver.v4.1.0.aarch64-linux-gnu-cxx03.tar.gz"
[[USRPHardwareDriver]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c8dc07cde0a95be56b411bb26e897ea8a3986176"
libc = "glibc"
os = "linux"

    [[USRPHardwareDriver.download]]
    sha256 = "ca08d1b9d826fa48bf029f7537ebac634a7f6edec6ac07433fd21e29132870a2"
    url = "https://github.com/JuliaBinaryWrappers/USRPHardwareDriver_jll.jl/releases/download/USRPHardwareDriver-v4.1.0+0/USRPHardwareDriver.v4.1.0.aarch64-linux-gnu-cxx11.tar.gz"
[[USRPHardwareDriver]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "884383bbc479dc2ba9d156befe12f77026ffea1c"
libc = "musl"
os = "linux"

    [[USRPHardwareDriver.download]]
    sha256 = "a4722c04c26cb99c0322f0ba65cdae1a28ad40c4c740b011ca5cd40dbb775a7a"
    url = "https://github.com/JuliaBinaryWrappers/USRPHardwareDriver_jll.jl/releases/download/USRPHardwareDriver-v4.1.0+0/USRPHardwareDriver.v4.1.0.aarch64-linux-musl-cxx03.tar.gz"
[[USRPHardwareDriver]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "468320f345960e42a9c3e7478255397ae396bb39"
libc = "musl"
os = "linux"

    [[USRPHardwareDriver.download]]
    sha256 = "9ff51e345a53952fcb6fa2918285afd80e087f871b54e1b1d81f35077c723097"
    url = "https://github.com/JuliaBinaryWrappers/USRPHardwareDriver_jll.jl/releases/download/USRPHardwareDriver-v4.1.0+0/USRPHardwareDriver.v4.1.0.aarch64-linux-musl-cxx11.tar.gz"
[[USRPHardwareDriver]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e4f6ed30d67e00c52ee038c82bf6caa3891b1b55"
libc = "glibc"
os = "linux"

    [[USRPHardwareDriver.download]]
    sha256 = "e2367f360c9a1aee48f16e4eddf2d3ea979109ed9cba6337a6babf66c123efc7"
    url = "https://github.com/JuliaBinaryWrappers/USRPHardwareDriver_jll.jl/releases/download/USRPHardwareDriver-v4.1.0+0/USRPHardwareDriver.v4.1.0.i686-linux-gnu-cxx03.tar.gz"
[[USRPHardwareDriver]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "79ccb940b97c97658a1fe6fd539accfd833ba1bc"
libc = "glibc"
os = "linux"

    [[USRPHardwareDriver.download]]
    sha256 = "6aca2be85ffa1a55294f17f90f4cfe48d59a88d9783f623736b14e586d906cd4"
    url = "https://github.com/JuliaBinaryWrappers/USRPHardwareDriver_jll.jl/releases/download/USRPHardwareDriver-v4.1.0+0/USRPHardwareDriver.v4.1.0.i686-linux-gnu-cxx11.tar.gz"
[[USRPHardwareDriver]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e16a0846e27b5d923d89cbeeb303a5821c41fb22"
libc = "musl"
os = "linux"

    [[USRPHardwareDriver.download]]
    sha256 = "1164cb313359d8da7ed566da3a352fc2bbadcf074ab0a278ebfecb076914f9d3"
    url = "https://github.com/JuliaBinaryWrappers/USRPHardwareDriver_jll.jl/releases/download/USRPHardwareDriver-v4.1.0+0/USRPHardwareDriver.v4.1.0.i686-linux-musl-cxx03.tar.gz"
[[USRPHardwareDriver]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "985ae9ea2b5099ea2dee7232567d2226dc8d498b"
libc = "musl"
os = "linux"

    [[USRPHardwareDriver.download]]
    sha256 = "af176b7ffb030c5715c7e63ffaa2406c1769abd20f2e5ea1a0d3249af241e418"
    url = "https://github.com/JuliaBinaryWrappers/USRPHardwareDriver_jll.jl/releases/download/USRPHardwareDriver-v4.1.0+0/USRPHardwareDriver.v4.1.0.i686-linux-musl-cxx11.tar.gz"
[[USRPHardwareDriver]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "91682953318b22d09d43fa47b6cafb8b2e630048"
libc = "glibc"
os = "linux"

    [[USRPHardwareDriver.download]]
    sha256 = "fa4b38c4d6506b32712a47cc4535c9ce7673be779b6227d57039960aa982050a"
    url = "https://github.com/JuliaBinaryWrappers/USRPHardwareDriver_jll.jl/releases/download/USRPHardwareDriver-v4.1.0+0/USRPHardwareDriver.v4.1.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[USRPHardwareDriver]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c6f7b06dc47038efc553e66bd31cdd03f6d6449e"
libc = "glibc"
os = "linux"

    [[USRPHardwareDriver.download]]
    sha256 = "2e924867690ecfd1446d1ae910f2dbbedea7bb1c464ee4b08af02ba3619ca07b"
    url = "https://github.com/JuliaBinaryWrappers/USRPHardwareDriver_jll.jl/releases/download/USRPHardwareDriver-v4.1.0+0/USRPHardwareDriver.v4.1.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[USRPHardwareDriver]]
arch = "x86_64"
git-tree-sha1 = "f0c28f69e32b0994a70c0df98e5be52abe0bfd3c"
os = "macos"

    [[USRPHardwareDriver.download]]
    sha256 = "223565c175591aae9f5bbc1fe71216c59e32b3e27e8564cf83933b9feeaa3435"
    url = "https://github.com/JuliaBinaryWrappers/USRPHardwareDriver_jll.jl/releases/download/USRPHardwareDriver-v4.1.0+0/USRPHardwareDriver.v4.1.0.x86_64-apple-darwin.tar.gz"
[[USRPHardwareDriver]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a92d223b13baf79b7b59919086abd625637f4885"
libc = "glibc"
os = "linux"

    [[USRPHardwareDriver.download]]
    sha256 = "c0fc2027ac1719122a9fc995d18883773c0aa9b412625fc09e5c65a1b7f4a35a"
    url = "https://github.com/JuliaBinaryWrappers/USRPHardwareDriver_jll.jl/releases/download/USRPHardwareDriver-v4.1.0+0/USRPHardwareDriver.v4.1.0.x86_64-linux-gnu-cxx03.tar.gz"
[[USRPHardwareDriver]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "aab01fd35ab3a7c6bbe0e50f3ae32adc1b8487c0"
libc = "glibc"
os = "linux"

    [[USRPHardwareDriver.download]]
    sha256 = "ed16d5f50bcdac9c35c904159a35392cdb3ec180c79613af01970ef9d104e037"
    url = "https://github.com/JuliaBinaryWrappers/USRPHardwareDriver_jll.jl/releases/download/USRPHardwareDriver-v4.1.0+0/USRPHardwareDriver.v4.1.0.x86_64-linux-gnu-cxx11.tar.gz"
[[USRPHardwareDriver]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c70449aa6d5195be4a504c3d31739b988cc9e843"
libc = "musl"
os = "linux"

    [[USRPHardwareDriver.download]]
    sha256 = "64ff8653020c4a77f45a34b91ae3ac7ab134f84da49b4247a03a3ab39a69892a"
    url = "https://github.com/JuliaBinaryWrappers/USRPHardwareDriver_jll.jl/releases/download/USRPHardwareDriver-v4.1.0+0/USRPHardwareDriver.v4.1.0.x86_64-linux-musl-cxx03.tar.gz"
[[USRPHardwareDriver]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e7c358656400381efc0df6399fed1a1ec36f10d9"
libc = "musl"
os = "linux"

    [[USRPHardwareDriver.download]]
    sha256 = "5a04a4ab6c92549332e57986ef71d3a81fd2301ef5232b5ccaca667cfef61cb2"
    url = "https://github.com/JuliaBinaryWrappers/USRPHardwareDriver_jll.jl/releases/download/USRPHardwareDriver-v4.1.0+0/USRPHardwareDriver.v4.1.0.x86_64-linux-musl-cxx11.tar.gz"
[[USRPHardwareDriver]]
arch = "x86_64"
git-tree-sha1 = "68f5b3c35b2eca2a33d3d1b314d18f20b6b58c27"
os = "freebsd"

    [[USRPHardwareDriver.download]]
    sha256 = "e4ac64e72ce2dc9609f8183da1fea3a8ebe56bf3b7d2f0df73b993ab9ecb013e"
    url = "https://github.com/JuliaBinaryWrappers/USRPHardwareDriver_jll.jl/releases/download/USRPHardwareDriver-v4.1.0+0/USRPHardwareDriver.v4.1.0.x86_64-unknown-freebsd.tar.gz"
