[[USRPHardwareDriver]]
arch = "aarch64"
git-tree-sha1 = "3fe605e4baef88b8af8c0fed9cb532390084eb7d"
os = "macos"

    [[USRPHardwareDriver.download]]
    sha256 = "1d79c7cb92ac471c6c856be2e5966908f10cb46010b073f475b7197e4aa0253c"
    url = "https://github.com/JuliaBinaryWrappers/USRPHardwareDriver_jll.jl/releases/download/USRPHardwareDriver-v4.1.0+1/USRPHardwareDriver.v4.1.0.aarch64-apple-darwin.tar.gz"
[[USRPHardwareDriver]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "29cb1da89a1afac6f05a0390c2d21d5027385e1e"
libc = "glibc"
os = "linux"

    [[USRPHardwareDriver.download]]
    sha256 = "8661df0830153200aae70627b0049917176567ae5d27aedc279d48c473450701"
    url = "https://github.com/JuliaBinaryWrappers/USRPHardwareDriver_jll.jl/releases/download/USRPHardwareDriver-v4.1.0+1/USRPHardwareDriver.v4.1.0.aarch64-linux-gnu-cxx03.tar.gz"
[[USRPHardwareDriver]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6387f27d7140c5b72f1c7fbdd62bee0b99634ff6"
libc = "glibc"
os = "linux"

    [[USRPHardwareDriver.download]]
    sha256 = "6d85d9036a40c941ad26dd5d62fbf34d359a5f032e114a67fd7929d85b865478"
    url = "https://github.com/JuliaBinaryWrappers/USRPHardwareDriver_jll.jl/releases/download/USRPHardwareDriver-v4.1.0+1/USRPHardwareDriver.v4.1.0.aarch64-linux-gnu-cxx11.tar.gz"
[[USRPHardwareDriver]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3192569317bba3219f932aa22c68522a65fa93d1"
libc = "musl"
os = "linux"

    [[USRPHardwareDriver.download]]
    sha256 = "50ea77c3aab7e2f4ddb522da781f90c37853e4297906d05832d868c9672fc76f"
    url = "https://github.com/JuliaBinaryWrappers/USRPHardwareDriver_jll.jl/releases/download/USRPHardwareDriver-v4.1.0+1/USRPHardwareDriver.v4.1.0.aarch64-linux-musl-cxx03.tar.gz"
[[USRPHardwareDriver]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a73a610d2ce471bf49fb383fe3a9a556edfc60a0"
libc = "musl"
os = "linux"

    [[USRPHardwareDriver.download]]
    sha256 = "88656ab4e21969cbfb7844f9ecdb937120ada0bb81dc06ca47aa772870a89219"
    url = "https://github.com/JuliaBinaryWrappers/USRPHardwareDriver_jll.jl/releases/download/USRPHardwareDriver-v4.1.0+1/USRPHardwareDriver.v4.1.0.aarch64-linux-musl-cxx11.tar.gz"
[[USRPHardwareDriver]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0e75184e0f6134bd7c985a90987a1ab89c9952c8"
libc = "glibc"
os = "linux"

    [[USRPHardwareDriver.download]]
    sha256 = "77255e6c794aa97d591d273e547df7c3dfc4c7cace7b405a80543dab0393dded"
    url = "https://github.com/JuliaBinaryWrappers/USRPHardwareDriver_jll.jl/releases/download/USRPHardwareDriver-v4.1.0+1/USRPHardwareDriver.v4.1.0.i686-linux-gnu-cxx03.tar.gz"
[[USRPHardwareDriver]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4efc7a90391937bf95c5cf2397a7c1e5f88a0a12"
libc = "glibc"
os = "linux"

    [[USRPHardwareDriver.download]]
    sha256 = "d89896347fb01233a617f59d7057d8f54fabfd2b93efae66e34b3984b7042aa3"
    url = "https://github.com/JuliaBinaryWrappers/USRPHardwareDriver_jll.jl/releases/download/USRPHardwareDriver-v4.1.0+1/USRPHardwareDriver.v4.1.0.i686-linux-gnu-cxx11.tar.gz"
[[USRPHardwareDriver]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "32f96107045b5c8522d0e3d38c89365203ddcd53"
libc = "musl"
os = "linux"

    [[USRPHardwareDriver.download]]
    sha256 = "9475c3305637dc4c66cedc9cf4d06fc3cd075f1bae45d182d04a81fc58f3d9fd"
    url = "https://github.com/JuliaBinaryWrappers/USRPHardwareDriver_jll.jl/releases/download/USRPHardwareDriver-v4.1.0+1/USRPHardwareDriver.v4.1.0.i686-linux-musl-cxx03.tar.gz"
[[USRPHardwareDriver]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c0002ba5dfe68b4f2839834db9040aa78d5b0e38"
libc = "musl"
os = "linux"

    [[USRPHardwareDriver.download]]
    sha256 = "b5e0629913c691d27b04d27e1a597bf891b08ad1e2e96cbd2323aa45837f4f18"
    url = "https://github.com/JuliaBinaryWrappers/USRPHardwareDriver_jll.jl/releases/download/USRPHardwareDriver-v4.1.0+1/USRPHardwareDriver.v4.1.0.i686-linux-musl-cxx11.tar.gz"
[[USRPHardwareDriver]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "825124ce9aef0780cdda4cad9f6b04e62464f1db"
libc = "glibc"
os = "linux"

    [[USRPHardwareDriver.download]]
    sha256 = "910a6abc3c4517e216b2eaf5300892f9f96139bb609ffe81ad2526b520888e2d"
    url = "https://github.com/JuliaBinaryWrappers/USRPHardwareDriver_jll.jl/releases/download/USRPHardwareDriver-v4.1.0+1/USRPHardwareDriver.v4.1.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[USRPHardwareDriver]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "98ddb8436c97a58f28a3ce44b6f346e13e5e753d"
libc = "glibc"
os = "linux"

    [[USRPHardwareDriver.download]]
    sha256 = "b0efe795a907a0d108019eb84ed41a6d552a9bd0eb2d36ca093383a46df008f1"
    url = "https://github.com/JuliaBinaryWrappers/USRPHardwareDriver_jll.jl/releases/download/USRPHardwareDriver-v4.1.0+1/USRPHardwareDriver.v4.1.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[USRPHardwareDriver]]
arch = "x86_64"
git-tree-sha1 = "aa6e145de0d3e767504f945ce1818457b0dd2b7f"
os = "macos"

    [[USRPHardwareDriver.download]]
    sha256 = "0d4a86504028a106626750ff73704baaac9a5af28c2035a4f7c3253d20130e5f"
    url = "https://github.com/JuliaBinaryWrappers/USRPHardwareDriver_jll.jl/releases/download/USRPHardwareDriver-v4.1.0+1/USRPHardwareDriver.v4.1.0.x86_64-apple-darwin.tar.gz"
[[USRPHardwareDriver]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7b0bce683d72c8b363069962673e59a71ff585e0"
libc = "glibc"
os = "linux"

    [[USRPHardwareDriver.download]]
    sha256 = "e0a94e9193343dec37241865c242be5a546a1cbb039b53d3ac25ef758bd2caa0"
    url = "https://github.com/JuliaBinaryWrappers/USRPHardwareDriver_jll.jl/releases/download/USRPHardwareDriver-v4.1.0+1/USRPHardwareDriver.v4.1.0.x86_64-linux-gnu-cxx03.tar.gz"
[[USRPHardwareDriver]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fabb2975097f0f0a96ef381e8e848891f4c68298"
libc = "glibc"
os = "linux"

    [[USRPHardwareDriver.download]]
    sha256 = "335cd42e709b186f73c7b03c8b8a7decd95c2d8aae3b1c2a15c3626b021b810b"
    url = "https://github.com/JuliaBinaryWrappers/USRPHardwareDriver_jll.jl/releases/download/USRPHardwareDriver-v4.1.0+1/USRPHardwareDriver.v4.1.0.x86_64-linux-gnu-cxx11.tar.gz"
[[USRPHardwareDriver]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "47970df46da855ee5ea3095ed92f2fa17e706c12"
libc = "musl"
os = "linux"

    [[USRPHardwareDriver.download]]
    sha256 = "287a972f0ab40579045c206b124b1245205e7252e624406618b357c1e69fde50"
    url = "https://github.com/JuliaBinaryWrappers/USRPHardwareDriver_jll.jl/releases/download/USRPHardwareDriver-v4.1.0+1/USRPHardwareDriver.v4.1.0.x86_64-linux-musl-cxx03.tar.gz"
[[USRPHardwareDriver]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "51276a84e26fdfded9e00434599f903d794dd975"
libc = "musl"
os = "linux"

    [[USRPHardwareDriver.download]]
    sha256 = "94f620a0ca2a1c9e9e402194027019040c5008f7607f8702169c4c87751e930e"
    url = "https://github.com/JuliaBinaryWrappers/USRPHardwareDriver_jll.jl/releases/download/USRPHardwareDriver-v4.1.0+1/USRPHardwareDriver.v4.1.0.x86_64-linux-musl-cxx11.tar.gz"
[[USRPHardwareDriver]]
arch = "x86_64"
git-tree-sha1 = "6eebd63c24167b4011be15fbba98673682648619"
os = "freebsd"

    [[USRPHardwareDriver.download]]
    sha256 = "169e61b34560c670d6f8b7de977d63034117a65b1a62da89a5d410af662c4041"
    url = "https://github.com/JuliaBinaryWrappers/USRPHardwareDriver_jll.jl/releases/download/USRPHardwareDriver-v4.1.0+1/USRPHardwareDriver.v4.1.0.x86_64-unknown-freebsd.tar.gz"
